### ISSUE TITLE
配置文件写入失败

### ISSUE THREAD

**Issue by hugcoday** [530003247/amango#1]
配置安装提示，配置文件写入失败，打开admin.php 也报下面的错，怎么回事呀
无法加载模块:Install
错误位置
FILE: D:\xampp\htdocs\amango\ThinkPHP\Library\Think\Dispatcher.class.php 　LINE: 171
TRACE
#0 D:\xampp\htdocs\amango\ThinkPHP\Library\Think\Dispatcher.class.php(171): E('\xE6\x97\xA0\xE6\xB3\x95\xE5\x8A\xA0\xE8\xBD\xBD\xE6\xA8\xA1...')
#1 D:\xampp\htdocs\amango\ThinkPHP\Library\Think\App.class.php(26): Think\Dispatcher::dispatch()
#2 D:\xampp\htdocs\amango\ThinkPHP\Library\Think\App.class.php(172): Think\App::init()
#3 D:\xampp\htdocs\amango\ThinkPHP\Library\Think\Think.class.php(117): Think\App::run()
#4 D:\xampp\htdocs\amango\ThinkPHP\ThinkPHP.php(94): Think\Think::start()
#5 D:\xampp\htdocs\amango\install.php(36): require('D:\xampp\htdocs...')
#6 {main}

**Comment by WhatAKitty** [comment]
@hugcoday 
@530003247 
同一个错误？？？

**Comment by blackcocwhite** [comment]
我也是报错，你们这个不做测试就提交吗
